//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientFollowUp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallLogType
    {
        public CallLogType()
        {
            this.CallLogs = new HashSet<CallLog>();
        }
    
        public int CallLogTypeId { get; set; }
        public string CallLogTypeText { get; set; }
    
        public virtual ICollection<CallLog> CallLogs { get; set; }
    }
}
