//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientFollowUp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallLog
    {
        public int CallLogId { get; set; }
        public string CallLogText { get; set; }
        public Nullable<int> CallLogTypeId { get; set; }
        public int FollowUpId { get; set; }
    
        public virtual CallLogType CallLogType { get; set; }
        public virtual FollowUp FollowUp { get; set; }
    }
}
