//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientFollowUp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilityType
    {
        public FacilityType()
        {
            this.FollowUps = new HashSet<FollowUp>();
            this.FollowUpHistories = new HashSet<FollowUpHistory>();
        }
    
        public int FacilityTypeId { get; set; }
        public string FacilityTypeDescription { get; set; }
    
        public virtual ICollection<FollowUp> FollowUps { get; set; }
        public virtual ICollection<FollowUpHistory> FollowUpHistories { get; set; }
    }
}
