//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientFollowUp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUp
    {
        public int FollowUpID { get; set; }
        public string PatientMRN { get; set; }
        public string ReferrerID { get; set; }
        public long AccessionNumber { get; set; }
        public string ExamType { get; set; }
        public System.DateTime FollowUpDate { get; set; }
        public int StatusID { get; set; }
        public Nullable<long> FollowUpExamID { get; set; }
        public string FollowUpCode { get; set; }
    }
}
