//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientFollowUp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUpCallLogType
    {
        public FollowUpCallLogType()
        {
            this.FollowUpCallLogs = new HashSet<FollowUpCallLog>();
        }
    
        public int FollowUpCallLogTypeId { get; set; }
        public string FollowUpCallLogTypeText { get; set; }
    
        public virtual ICollection<FollowUpCallLog> FollowUpCallLogs { get; set; }
    }
}
