//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientFollowUp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUpCode
    {
        public int FollowUpCode_Id { get; set; }
        public string FollowUpCode1 { get; set; }
        public string FollowUpType { get; set; }
        public string ExamType { get; set; }
        public string PathologyCode { get; set; }
        public Nullable<short> Days { get; set; }
    }
}
