//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientFollowUp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkList
    {
        public long WorkListId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public string Task { get; set; }
        public string ExamNumber { get; set; }
        public string InsurancePlan { get; set; }
        public string Modality { get; set; }
        public Nullable<System.DateTime> ScheduledDateTime { get; set; }
        public Nullable<int> WorkListStatusId { get; set; }
        public string RisStatus { get; set; }
        public string AssignedUser { get; set; }
    
        public virtual WorkListStatu WorkListStatu { get; set; }
    }
}
