//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientFollowUp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkListStatu
    {
        public WorkListStatu()
        {
            this.WorkLists = new HashSet<WorkList>();
        }
    
        public int WorkListStatusId { get; set; }
        public string StatusName { get; set; }
        public string StatusDescription { get; set; }
    
        public virtual ICollection<WorkList> WorkLists { get; set; }
    }
}
